2021-01-10 12:48:05,488 - GPTime.model.train - INFO - Device: cuda:0
2021-01-10 12:48:05,529 - GPTime.networks.mlp - DEBUG - Input size of model: 256.
2021-01-10 12:48:05,529 - GPTime.networks.mlp - DEBUG - Number of layers: 10.
2021-01-10 12:48:05,529 - GPTime.networks.mlp - DEBUG - Number of hidden units: 512.
2021-01-10 12:48:06,766 - GPTime.model.train - INFO - Number of learnable parameters: 2233345
2021-01-10 12:48:06,772 - GPTime.model.train - INFO - Using learning rate sheduler: None
2021-01-10 12:48:06,772 - GPTime.model.train - INFO - Not using a validation set. Training on the full dataset.
2021-01-10 12:48:06,772 - GPTime.model.data - INFO - Total of 0 time series in memory.
2021-01-10 12:48:06,773 - GPTime.model.data - INFO - Frequencies: {'D': True, 'H': True, 'M': True, 'O': True, 'Q': True, 'W': True, 'Y': True}.
2021-01-10 12:48:06,773 - GPTime.model.train - INFO - seasonal init: False
2021-01-10 12:48:06,773 - GPTime.model.train - INFO - Training model.
2021-01-10 12:48:06,773 - GPTime.model.train - INFO - Length of dataset: 0
2021-01-10 12:48:06,773 - GPTime.run - ERROR - Task train failed
Traceback (most recent call last):
  File "/share/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/GPTime/__main__.py", line 5, in <module>
    main_cli()
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/GPTime/run.py", line 50, in main_cli
    main(task, task_cfg)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/GPTime/run.py", line 33, in main
    tasks[task](task_cfg)
  File "/lustre1/home/erikde/master_thesis/GPTime-Series/GPTime/model/train.py", line 215, in train
    running_loss += epoch_loss / batches_non_inf
ZeroDivisionError: float division by zero
